"""Regenerate fermium/units_selfhosted.py from units_db.fm:  python3 -m fermium.selfhost [--check]"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "units_selfhosted.py")
SUPER = str.maketrans("⁻⁰¹²³⁴⁵⁶⁷⁸⁹", "-0123456789")


def parse_number(text):
    if "×10" in text:
        mant, ex = text.split("×10")
        return float(mant) * 10.0 ** int(ex.translate(SUPER))
    return float(text)


def run_db(src=None):
    """Compile and run units_db.fm with the existing compiler; returns {unit name: SI factor}.  Every
    printed factor must be a plain number: a definition with the wrong dimension leaves a unit behind
    (a light year divided by a metre is a number, a speed divided by a metre is 1/s) and is rejected."""
    from fermium.driver import run_source
    import io
    if src is None:
        src = open(os.path.join(HERE, "units_db.fm"), encoding="utf-8").read()
    out = io.StringIO()
    run_source(src, "units_db.fm", out=out)
    table = {}
    for line in out.getvalue().splitlines():
        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"units_db.fm: the definition of {parts[0]} has the wrong dimension "
                             f"(it came out as {' '.join(parts[1:])}, not a plain number)")
        table[parts[0]] = parse_number(parts[1])
    return table


def render(table):
    lines = ['"""GENERATED by `python3 -m fermium.selfhost` from fermium/selfhost/units_db.fm (a Fermium program',
             'compiled by Fermium).  Do not edit: change units_db.fm and regenerate.  tests/test_selfhost.py checks',
             'that this file is up to date."""', "", "FACTORS = {"]
    for name, value in table.items():
        lines.append(f"    {name!r}: {value!r},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv):
    text = render(run_db())
    if "--check" in argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("fermium/units_selfhosted.py is out of date: run python3 -m fermium.selfhost")
            return 1
        print("up to date")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
