//! `import cpp` (spec C4, DECISIONS D290): C++ functions through a generated `extern "C"` wrapper.
//!
//! ```text
//! import cpp "libphys.so" header "phys.hpp":
//!     phys::kinetic_energy(m [kg], v [m/s]) -> [J]
//!     phys::energy(m [kg]) -> [J] as rest_energy            # one overload of phys::energy …
//!     phys::energy(m [kg], v [m/s]) -> [J] as total_energy  # … and another
//!     phys::Particle::compton_wavelength(m [kg]) -> [m]     # a static member function
//! ```
//!
//! For each signature Fermium writes a small C function into one C++ file: it takes the parameters as C types
//! (`double` for a number, `int` for `: int` and `len(…)`, a pointer to doubles for `: list`), picks the C++
//! function by converting `&phys::energy` to the function-pointer type the signature declares (so the declared
//! signature chooses among overloads, exactly, and deduces a function template's arguments), calls it inside a
//! `try` (an exception must not unwind into Fermium: its message is kept for `fermium_cpp_error`), and returns
//! the result. The file is compiled with the system's C++ compiler (`$CXX`, else c++, g++, clang++) into a shared
//! library linked against the program's library, kept in Fermium's private cache folder (`cpp/`, cachedir.rs)
//! under the SHA-256 of everything that changes the compile, with a manifest of every file the compiler read,
//! and reused only while that manifest still matches (D320). From there on a C++ function is a C function of
//! the wrapper, called by C3's machinery (cinterop.rs), units checked at every call.
use std::path::{Path, PathBuf};
use std::process::Command;

use fermium_syntax::ast as A;

/// A signature as the wrapper needs it: the qualified C++ name in ASCII, the parameter kinds and the result.
pub struct CppSig {
    pub qual: String,
    pub params: Vec<A::CParamKind>,
    pub rint: bool,
}

/// Why a wrapper couldn't be made: the message, its hint, and the signature it is about (None: the import line).
#[derive(Debug)]
pub struct CppError {
    pub sig: Option<usize>,
    pub msg: String,
    pub hint: Option<String>,
}

fn cerr(sig: Option<usize>, msg: impl Into<String>, hint: Option<String>) -> CppError {
    CppError { sig, msg: msg.into(), hint }
}

/// The C type of a parameter; `mutable` spells a list as `double *` instead of `const double *`.
fn ctype(k: &A::CParamKind, mutable: bool) -> &'static str {
    match k {
        A::CParamKind::Num(_) => "double",
        A::CParamKind::Int | A::CParamKind::Len(_) => "int",
        A::CParamKind::List(_) => {
            if mutable {
                "double *"
            } else {
                "const double *"
            }
        }
    }
}

/// `double(double, int)`: the C++ type a signature asks for (lists as `const double *`), for messages.
pub fn cpp_type(sig: &CppSig) -> String {
    let ps: Vec<&str> = sig.params.iter().map(|p| ctype(p, false)).collect();
    format!("{}({})", if sig.rint { "int" } else { "double" }, ps.join(", "))
}

/// The symbol of signature k's C function in the wrapper.
pub fn wrapper_symbol(k: usize) -> String {
    format!("fermium_cpp_{k}")
}

/// The wrapper's C++ source, and the lines (1-based, inclusive) each signature's code spans.
/// A header the program's folder doesn't have (`system`) is included as `<name>`, found on the compiler's own
/// include path.
pub fn wrapper_source(include: &str, system: bool, sigs: &[CppSig]) -> (String, Vec<(usize, usize)>, usize) {
    let mut out: Vec<String> = vec![
        "// Generated by Fermium for  import cpp  (C4, DECISIONS D290); it is made again when it changes.".into(),
        "#include <cstdio>".into(),
        "#include <cstring>".into(),
        "#include <exception>".into(),
    ];
    if system {
        out.push(format!("#include <{include}>"));
    } else {
        let quoted = include.replace('\\', "\\\\").replace('"', "\\\"");
        out.push(format!("#include \"{quoted}\""));
    }
    let include_line = out.len();
    out.extend(
        r#"
static thread_local char fermium_cpp_msg[512];

static void fermium_cpp_threw(const char *f, const char *what) {
    if (what && *what)
        std::snprintf(fermium_cpp_msg, sizeof fermium_cpp_msg, "the C++ function %s threw an exception: %s", f, what);
    else
        std::snprintf(fermium_cpp_msg, sizeof fermium_cpp_msg, "the C++ function %s threw an exception", f);
    // one line of plain text: line breaks, tabs and escape codes in what() become spaces
    for (char *p = fermium_cpp_msg; *p; ++p)
        if ((unsigned char)*p < 0x20 || *p == 0x7f) *p = ' ';
}

// the message of the exception the last call threw (0: none), cleared
extern "C" int fermium_cpp_error(char *buf, int n) {
    int len = (int)std::strlen(fermium_cpp_msg);
    if (len == 0 || n <= 0) return 0;
    if (len > n - 1) len = n - 1;
    std::memcpy(buf, fermium_cpp_msg, len);
    buf[len] = 0;
    fermium_cpp_msg[0] = 0;
    return len;
}"#
        .lines()
        .map(str::to_string),
    );
    let mut ranges = vec![];
    for (k, s) in sigs.iter().enumerate() {
        out.push(String::new());
        let first = out.len() + 1;
        let ret = if s.rint { "int" } else { "double" };
        let names: Vec<String> = (0..s.params.len()).map(|j| format!("a{j}")).collect();
        let decl: Vec<String> = s.params.iter().zip(&names).map(|(p, n)| format!("{} {n}", ctype(p, true))).collect();
        let lists: Vec<usize> = (0..s.params.len()).filter(|&j| matches!(s.params[j], A::CParamKind::List(_))).collect();
        // one helper per spelling of the lists (const double * or double *): converting &f to the helper's
        // parameter picks the overload with exactly these parameter types
        let variants = if lists.len() <= 3 { 1usize << lists.len() } else { 1 };
        out.push(format!("// {}: {}", s.qual, cpp_type(s)));
        for v in 0..variants {
            let types: Vec<&str> = s.params.iter().enumerate()
                .map(|(j, p)| ctype(p, lists.iter().position(|&l| l == j).is_some_and(|b| v >> b & 1 == 1)))
                .collect();
            let mut hp = vec![format!("{ret} (*f)({})", types.join(", "))];
            hp.extend(decl.iter().cloned());
            out.push(format!("static inline {ret} fermium_cpp_call_{k}({}) {{ return f({}); }}", hp.join(", "),
                             names.join(", ")));
        }
        let mut cargs = vec![format!("&{}", s.qual)];
        cargs.extend(names.iter().cloned());
        out.push(format!("extern \"C\" {ret} {}({}) {{", wrapper_symbol(k), decl.join(", ")));
        out.push("    try {".into());
        out.push(format!("        return fermium_cpp_call_{k}({});", cargs.join(", ")));
        out.push("    } catch (const std::exception &e) {".into());
        out.push(format!("        fermium_cpp_threw(\"{}\", e.what());", s.qual));
        out.push("    } catch (...) {".into());
        out.push(format!("        fermium_cpp_threw(\"{}\", nullptr);", s.qual));
        out.push("    }".into());
        out.push("    return 0;".into());
        out.push("}".into());
        ranges.push((first, out.len()));
    }
    let mut src = out.join("\n");
    src.push('\n');
    (src, ranges, include_line)
}

/// Where compiled wrappers are kept: `cpp/` in Fermium's cache folder (cachedir.rs).
pub fn cache_dir() -> PathBuf {
    crate::cachedir::root().join("cpp")
}

/// A file's size and modification time (ns since 1970), or None when it isn't there.
fn stamp(p: &Path) -> Option<(u64, u128)> {
    let m = std::fs::metadata(p).ok()?;
    let t = m.modified().ok()?.duration_since(std::time::UNIX_EPOCH).ok()?.as_nanos();
    Some((m.len(), t))
}

/// The files a make-style dependency file (`-MD`) lists.
fn deps_of(d: &str) -> Vec<PathBuf> {
    let joined = d.replace("\\\n", " ");
    let Some((_, rest)) = joined.split_once(": ") else { return vec![] };
    let mut out = vec![];
    let mut cur = String::new();
    let mut it = rest.chars().peekable();
    while let Some(c) = it.next() {
        match c {
            '\\' if it.peek() == Some(&' ') => {
                cur.push(' ');
                it.next();
            }
            ' ' | '\n' | '\t' => {
                if !cur.is_empty() {
                    out.push(PathBuf::from(std::mem::take(&mut cur)));
                }
            }
            c => cur.push(c),
        }
    }
    if !cur.is_empty() {
        out.push(PathBuf::from(cur));
    }
    out
}

/// The program `prog` as the shell would find it on the PATH (or the path itself, when it has a slash).
fn which(prog: &str) -> Option<PathBuf> {
    let runnable = |p: &Path| {
        let Ok(m) = std::fs::metadata(p) else { return false };
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            m.is_file() && m.permissions().mode() & 0o111 != 0
        }
        #[cfg(not(unix))]
        {
            m.is_file()
        }
    };
    if prog.contains('/') {
        let p = PathBuf::from(prog);
        return runnable(&p).then_some(p);
    }
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path).map(|d| d.join(prog)).find(|c| runnable(c))
}

/// The C++ compiler: `$CXX` (which may carry arguments, like `ccache g++`), else the first of c++, g++, clang++
/// on the PATH.
fn find_cxx() -> Option<Vec<String>> {
    if let Some(c) = std::env::var("CXX").ok().filter(|v| !v.trim().is_empty()) {
        return Some(c.split_whitespace().map(str::to_string).collect());
    }
    ["c++", "g++", "clang++"].iter().find(|c| which(c).is_some()).map(|c| vec![c.to_string()])
}

/// Which compiler this is, without running it: each word of the command that names a program, as the file it
/// resolves to (links followed) with its size and time, so another compiler, or the same one updated, differs.
fn compiler_identity(cxx: &[String]) -> String {
    cxx.iter().map(|w| match which(w).map(|p| std::fs::canonicalize(&p).unwrap_or(p)) {
        Some(p) => match stamp(&p) {
            Some((n, t)) => format!("{}\t{n}\t{t}", p.display()),
            None => p.display().to_string(),
        },
        None => w.clone(),
    }).collect::<Vec<_>>().join("\n")
}

/// The environment variables that change what the compiler includes or links (so they are part of the key).
const CXX_ENV: [&str; 10] = ["CXX", "CXXFLAGS", "CPATH", "CPLUS_INCLUDE_PATH", "C_INCLUDE_PATH", "LIBRARY_PATH",
                             "GCC_EXEC_PREFIX", "COMPILER_PATH", "SDKROOT", "MACOSX_DEPLOYMENT_TARGET"];

/// How long the C++ compiler may take: `$FERMIUM_CXX_TIMEOUT` seconds, else 120.
fn cxx_timeout() -> u64 {
    std::env::var("FERMIUM_CXX_TIMEOUT").ok().and_then(|v| v.trim().parse().ok()).filter(|&s| s > 0).unwrap_or(120)
}

enum RunErr {
    Io(std::io::Error),
    Timeout,
}

/// Run `cmd` to the end, or stop it (and everything it started) after `secs` seconds.
fn run_limited(cmd: &mut Command, secs: u64) -> Result<std::process::Output, RunErr> {
    use std::io::Read;
    use std::process::Stdio;
    cmd.stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::piped());
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        cmd.process_group(0);
    }
    let mut child = cmd.spawn().map_err(RunErr::Io)?;
    let (mut so, mut se) = (child.stdout.take(), child.stderr.take());
    let to = std::thread::spawn(move || {
        let mut v = vec![];
        if let Some(s) = so.as_mut() {
            let _ = s.read_to_end(&mut v);
        }
        v
    });
    let te = std::thread::spawn(move || {
        let mut v = vec![];
        if let Some(s) = se.as_mut() {
            let _ = s.read_to_end(&mut v);
        }
        v
    });
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(secs);
    let mut nap = 1;
    let status = loop {
        match child.try_wait() {
            Ok(Some(s)) => break s,
            Ok(None) => {}
            Err(e) => return Err(RunErr::Io(e)),
        }
        if std::time::Instant::now() >= deadline {
            #[cfg(unix)]
            {
                extern "C" {
                    fn kill(pid: i32, sig: i32) -> i32;
                }
                // SAFETY: signals the process group this child leads (made above); 9 is SIGKILL
                unsafe {
                    kill(-(child.id() as i32), 9);
                }
            }
            let _ = child.kill();
            let _ = child.wait();
            return Err(RunErr::Timeout);
        }
        std::thread::sleep(std::time::Duration::from_millis(nap));
        nap = (nap * 2).min(25);
    };
    Ok(std::process::Output { status, stdout: to.join().unwrap_or_default(), stderr: te.join().unwrap_or_default() })
}

/// The manifest kept next to a wrapper (`<stem>.manifest`): what it was built from, checked before it is reused.
///
/// ```text
/// fermium-cpp-manifest 2
/// compiler <SHA-256 of the compiler's identity>
/// version <SHA-256 of its --version output>
/// so <size> <SHA-256 of the wrapper>
/// lib <size> <mtime> <path>
/// dep <size> <mtime> <path>          (every file the compiler read, from its -MD list)
/// ```
fn manifest_ok(man: &Path, so: &Path, compiler: Option<&str>, lib: Option<&Path>) -> bool {
    let Ok(text) = std::fs::read_to_string(man) else { return false };
    let mut lines = text.lines();
    if lines.next() != Some("fermium-cpp-manifest 2") {
        return false;
    }
    let (mut saw_so, mut saw_lib, mut deps) = (false, false, 0);
    for line in lines {
        let (tag, rest) = line.split_once(' ').unwrap_or((line, ""));
        match tag {
            // with no compiler on the PATH a wrapper is still reused (nothing else could be built)
            "compiler" => {
                if compiler.is_some_and(|c| crate::sha256::hex(c.as_bytes()) != rest) {
                    return false;
                }
            }
            "version" => {}
            "so" => {
                let Some((n, h)) = rest.split_once(' ') else { return false };
                let Ok(bytes) = std::fs::read(so) else { return false };
                if bytes.len().to_string() != n || crate::sha256::hex(&bytes) != h {
                    return false;
                }
                saw_so = true;
            }
            "lib" | "dep" => {
                let mut f = rest.splitn(3, ' ');
                let (Some(n), Some(t), Some(p)) = (f.next(), f.next(), f.next()) else { return false };
                if tag == "lib" {
                    if lib != Some(Path::new(p)) {
                        return false;
                    }
                    saw_lib = true;
                } else {
                    deps += 1;
                }
                match stamp(Path::new(p)) {
                    Some((sn, st)) if sn.to_string() == n && st.to_string() == t => {}
                    _ => return false,
                }
            }
            _ => return false,
        }
    }
    saw_so && deps > 0 && saw_lib == lib.is_some()
}

/// Everything a wrapper is made from.
pub struct CppImport<'a> {
    /// the library as written ("" for a header-only import) and its path (absolute when it is a file)
    pub lib: &'a str,
    pub lib_path: &'a str,
    /// the header as written, and what the wrapper includes: the header's absolute path when the program's
    /// folder has it, else the name as written, found by the compiler on its own include path (`system`)
    pub header: &'a str,
    pub include: String,
    pub system: bool,
    /// the program's folder (on the include path, for a header of the program's own)
    pub base: &'a str,
    pub sigs: Vec<CppSig>,
}

/// The wrapper's path, compiled now unless the cache has it (DECISIONS D290, D320).
///
/// The cache key is the SHA-256 of everything known before compiling that changes the result: the wrapper's
/// source (which names the header and the signatures), whether the header is the program's or a system one,
/// the header's text, the `-I` folders, the environment variables that change what the compiler includes or
/// links (`CXX_ENV`) and the library as written and its path. Next to the wrapper is a manifest of what it
/// was built from: the compiler's identity, every file the compiler read (its `-MD` list, system headers
/// included) and the library, each with its size and time, and the wrapper's own SHA-256. A cached wrapper is
/// used only when all of these still match. A header the program's folder doesn't have is included as
/// `<name>` with no `-I` folder, so a file in the program's folder can't stand in for a system header.
pub fn build_wrapper(imp: &CppImport) -> Result<String, CppError> {
    let (src, ranges, include_line) = wrapper_source(&imp.include, imp.system, &imp.sigs);
    let mut inc_dirs: Vec<String> = vec![];
    if !imp.system {
        inc_dirs.push(imp.base.to_string());
        if let Some(parent) = Path::new(&imp.include).parent().filter(|p| p.is_absolute()) {
            let p = parent.to_string_lossy().into_owned();
            if !inc_dirs.contains(&p) {
                inc_dirs.push(p);
            }
        }
    }
    let flags = std::env::var("CXXFLAGS").unwrap_or_default();
    let key = {
        let mut h = crate::sha256::Sha256::new();
        h.field(b"fermium-cpp-2");
        h.field(src.as_bytes());
        h.field(if imp.system { b"system" } else { b"local" });
        h.field(imp.include.as_bytes());
        h.field(&if imp.system { vec![] } else { std::fs::read(&imp.include).unwrap_or_default() });
        h.field(&(inc_dirs.len() as u64).to_le_bytes());
        for d in &inc_dirs {
            h.field(d.as_bytes());
        }
        for k in CXX_ENV {
            h.field(k.as_bytes());
            h.field(std::env::var_os(k).map(|v| v.to_string_lossy().into_owned()).unwrap_or_default().as_bytes());
        }
        h.field(imp.lib.as_bytes());
        h.field(imp.lib_path.as_bytes());
        h.hex()
    };
    let (dir, cached) = match crate::cachedir::private_dir("cpp") {
        Ok(d) => (d, true),
        Err((msg, hint)) => {
            crate::cachedir::warn_once(&msg, &hint);
            match crate::cachedir::private_temp_dir("cpp") {
                Ok(d) => (d, false),
                Err(e) => return Err(cerr(None, format!("can't make a folder for the compiled C++ wrapper: {e}"),
                                          Some("set FERMIUM_CACHE_DIR to a folder of your own".into()))),
            }
        }
    };
    let stem = format!("w{}", &key[..40]);
    let so = dir.join(format!("{stem}.so"));
    let man = dir.join(format!("{stem}.manifest"));
    let lib_file = Some(Path::new(imp.lib_path)).filter(|p| !imp.lib.is_empty() && p.is_absolute());
    let cxx = find_cxx();
    let identity = cxx.as_deref().map(compiler_identity);
    if cached && manifest_ok(&man, &so, identity.as_deref(), lib_file) {
        return Ok(so.to_string_lossy().into_owned());
    }
    let Some(cxx) = cxx else {
        return Err(cerr(None, "import cpp needs a C++ compiler, and none was found (tried c++, g++ and clang++)",
                        Some("install one (like  sudo apt install g++), or set CXX to its path".into())));
    };
    let identity = identity.unwrap_or_default();
    let secs = cxx_timeout();
    let pid = std::process::id();
    let cpp = dir.join(format!("{stem}.cpp"));
    let tmp_cpp = dir.join(format!("{stem}.{pid}.cpp.tmp"));
    let tmp_so = dir.join(format!("{stem}.{pid}.so.tmp"));
    let tmp_d = dir.join(format!("{stem}.{pid}.d.tmp"));
    let tmp_man = dir.join(format!("{stem}.{pid}.manifest.tmp"));
    let log = dir.join(format!("{stem}.log"));
    let _ = std::fs::remove_file(&man);
    let write = std::fs::write(&tmp_cpp, &src).and_then(|_| std::fs::rename(&tmp_cpp, &cpp));
    if let Err(e) = write {
        return Err(cerr(None, format!("can't write the C++ wrapper {}: {e}", cpp.display()), None));
    }
    let mut cmd = Command::new(&cxx[0]);
    cmd.args(&cxx[1..]).args(["-x", "c++", "-std=c++17", "-O2", "-fPIC", "-shared", "-MD", "-MF"]).arg(&tmp_d);
    for d in &inc_dirs {
        cmd.arg("-I").arg(d);
    }
    cmd.arg("-o").arg(&tmp_so).arg(&cpp).args(["-x", "none"]);
    if !imp.lib.is_empty() {
        let lp = Path::new(imp.lib_path);
        if lp.is_absolute() {
            cmd.arg(lp);
            if let Some(parent) = lp.parent() {
                cmd.arg(format!("-Wl,-rpath,{}", parent.display()));
            }
        } else {
            cmd.arg(format!("-l:{}", imp.lib_path));
        }
    }
    if cfg!(target_os = "linux") {
        cmd.arg("-Wl,--no-undefined");
    }
    cmd.args(flags.split_whitespace());
    let out = match run_limited(&mut cmd, secs) {
        Ok(o) => o,
        Err(RunErr::Timeout) => {
            let _ = std::fs::remove_file(&tmp_so);
            let _ = std::fs::remove_file(&tmp_d);
            return Err(cerr(None, format!("the C++ compiler {} didn't finish within {secs} s, so it was stopped", cxx[0]),
                            Some("set FERMIUM_CXX_TIMEOUT to the seconds it may take, if the header is just slow \
                                  to compile".into())));
        }
        Err(RunErr::Io(e)) => {
            return Err(cerr(None, format!("can't run the C++ compiler {}: {e}", cxx[0]),
                            Some("set CXX to a C++ compiler's path".into())));
        }
    };
    let stderr = String::from_utf8_lossy(&out.stderr).into_owned();
    if !out.status.success() {
        let _ = std::fs::write(&log, format!("{:?}\n\n{stderr}", cmd));
        let _ = std::fs::remove_file(&tmp_so);
        let _ = std::fs::remove_file(&tmp_d);
        return Err(summarise(&stderr, imp, &cpp, &ranges, include_line, &log));
    }
    // the manifest; without one (a path with a line break in it) the wrapper is used this once and not reused
    let deps = std::fs::read_to_string(&tmp_d).map(|d| deps_of(&d)).unwrap_or_default();
    let _ = std::fs::remove_file(&tmp_d);
    let so_bytes = std::fs::read(&tmp_so).unwrap_or_default();
    let version = run_limited(Command::new(&cxx[0]).args(&cxx[1..]).arg("--version"), secs.min(20))
        .map(|o| crate::sha256::hex(&[o.stdout, o.stderr].concat())).unwrap_or_default();
    let mut m = vec!["fermium-cpp-manifest 2".to_string(),
                     format!("compiler {}", crate::sha256::hex(identity.as_bytes())),
                     format!("version {version}"),
                     format!("so {} {}", so_bytes.len(), crate::sha256::hex(&so_bytes))];
    let mut good = !so_bytes.is_empty();
    if let Some(lp) = lib_file {
        match stamp(lp) {
            Some((n, t)) => m.push(format!("lib {n} {t} {}", lp.display())),
            None => good = false,
        }
    }
    let mut ndeps = 0;
    for d in deps.iter().filter(|d| d.as_path() != cpp.as_path()) {
        let d = if d.is_absolute() {
            d.clone()
        } else {
            std::env::current_dir().map(|c| c.join(d)).unwrap_or(d.clone())
        };
        match stamp(&d) {
            Some((n, t)) => m.push(format!("dep {n} {t} {}", d.display())),
            None => good = false,
        }
        ndeps += 1;
    }
    good &= ndeps > 0 && m.iter().all(|l| !l.contains('\n') && !l.contains('\r'));
    if let Err(e) = std::fs::rename(&tmp_so, &so) {
        return Err(cerr(None, format!("can't store the compiled C++ wrapper in {}: {e}", dir.display()), None));
    }
    if good && cached {
        let mut text = m.join("\n");
        text.push('\n');
        if std::fs::write(&tmp_man, text).and_then(|_| std::fs::rename(&tmp_man, &man)).is_err() {
            let _ = std::fs::remove_file(&tmp_man);
        }
    }
    Ok(so.to_string_lossy().into_owned())
}

/// The compiler's complaint in one line, about the signature it concerns.
fn summarise(stderr: &str, imp: &CppImport, cpp: &Path, ranges: &[(usize, usize)], include_line: usize, log: &Path)
             -> CppError {
    let full = Some(format!("the compiler's full output is in {}", log.display()));
    let mapping = "Fermium passes a number ([unit] or plain) as double, : int and len(…) as int and : list as const \
                   double * (or double *), and expects double back (-> [unit], -> number) or int (-> int)";
    let cpp_s = cpp.to_string_lossy();
    for line in stderr.lines() {
        // link errors (GNU ld, lld, macOS ld)
        let undefined = line.split_once("undefined reference to `").map(|x| x.1.trim_end_matches('\''))
            .or_else(|| line.split_once("undefined symbol: ").map(|x| x.1.trim()));
        if let Some(sym) = undefined {
            let sig = imp.sigs.iter().position(|s| sym.starts_with(&format!("{}(", s.qual)) || sym == s.qual);
            return if imp.lib.is_empty() {
                cerr(sig, format!("{sym} is declared in {} but defined nowhere: the import names no library",
                                  imp.header),
                     Some(format!("name the library before the header, like  import cpp \"libfoo.so\" header \"{}\"",
                                  imp.header)))
            } else {
                cerr(sig, format!("the C++ library {} has no definition of {sym}", imp.lib),
                     Some(format!("the header declares it: check that the library is built from the same sources \
                                   (nm -DC {} lists the functions it defines)", imp.lib)))
            };
        }
        let Some((at, msg)) = line.split_once(": fatal error: ").or_else(|| line.split_once(": error: ")) else {
            continue;
        };
        let msg = msg.trim();
        let mut parts = at.rsplitn(3, ':').collect::<Vec<_>>();
        parts.reverse();
        // file:line:col, file:line, or a tool's name (a link error without a location)
        let (file, lno) = match parts.as_slice() {
            [f, l, c] if l.parse::<usize>().is_ok() && c.parse::<usize>().is_ok() => (f.to_string(), l.parse().unwrap()),
            [f, l, c] if c.parse::<usize>().is_ok() => (format!("{f}:{l}"), c.parse().unwrap()),
            [f, l] if l.parse::<usize>().is_ok() => (f.to_string(), l.parse().unwrap()),
            _ => (String::new(), 0usize),
        };
        if file.is_empty() {
            continue;
        }
        if file == cpp_s {
            if lno == include_line || msg.contains("No such file") || msg.contains("file not found") {
                return cerr(None, format!("can't find the header {}", imp.header),
                            Some("it isn't in the program's folder (a path is relative to it) or on the C++ \
                                  compiler's include path (add folders with CPATH)".into()));
            }
            let Some(k) = ranges.iter().position(|&(a, b)| (a..=b).contains(&lno)) else {
                return cerr(None, format!("the C++ wrapper didn't compile: {msg}"), full);
            };
            let s = &imp.sigs[k];
            let has = |ws: &[&str]| ws.iter().any(|w| msg.contains(w));
            if has(&["is not a member of", "no member named", "was not declared", "undeclared identifier",
                     "has not been declared", "does not name", "is not a class, namespace", "not a class or namespace"]) {
                return cerr(Some(k), format!("the header {} declares no function {}", imp.header, s.qual),
                            Some("check the spelling and the namespace (C++ names are case-sensitive)".into()));
            }
            // a non-static member function: &Class::f is a pointer to member
            if stderr.contains("::*)") {
                return cerr(Some(k), format!("{} is a member function, which needs an object; only free functions and \
                                              static member functions can be imported", s.qual),
                            Some("add a free (or static) function to the library that makes the object and calls it"
                                .into()));
            }
            if has(&["ambiguous"]) {
                return cerr(Some(k), format!("more than one overload of {} has the C++ type {}", s.qual, cpp_type(s)),
                            Some(mapping.into()));
            }
            if has(&["no matching function", "invalid conversion", "no known conversion", "cannot initialize",
                     "no matches converting", "overloaded function", "cannot convert", "invalid static_cast"]) {
                return cerr(Some(k), format!("no overload of {} has the C++ type {}", s.qual, cpp_type(s)),
                            Some(mapping.into()));
            }
            return cerr(Some(k), format!("the C++ wrapper for {} didn't compile: {msg}", s.qual), full);
        }
        let shown = Path::new(&file).file_name().map(|f| f.to_string_lossy().into_owned()).unwrap_or(file.clone());
        return cerr(None, format!("the header {} doesn't compile: {shown}, line {lno}: {msg}", imp.header), full);
    }
    let first = stderr.lines().map(str::trim).find(|l| !l.is_empty()).unwrap_or("no message");
    cerr(None, format!("compiling the C++ wrapper failed: {first}"), full)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_wrapper_picks_the_declared_overload_through_a_function_pointer() {
        let sigs = vec![
            CppSig { qual: "phys::energy".into(), params: vec![A::CParamKind::Num(None), A::CParamKind::Int], rint: false },
            CppSig { qual: "sum".into(), params: vec![A::CParamKind::List(None), A::CParamKind::Len("x".into())],
                     rint: true },
        ];
        let (src, ranges, inc) = wrapper_source("/x/phys.hpp", false, &sigs);
        let lines: Vec<&str> = src.lines().collect();
        assert_eq!(lines[inc - 1], "#include \"/x/phys.hpp\"");
        assert!(src.contains("static inline double fermium_cpp_call_0(double (*f)(double, int), double a0, int a1) \
                              { return f(a0, a1); }"), "{src}");
        assert!(src.contains("return fermium_cpp_call_0(&phys::energy, a0, a1);"), "{src}");
        // a list may be const double * or double * in the C++ function
        assert!(src.contains("int (*f)(const double *, int)") && src.contains("int (*f)(double *, int)"), "{src}");
        assert!(src.contains("extern \"C\" int fermium_cpp_1(double * a0, int a1) {"), "{src}");
        assert_eq!(ranges.len(), 2);
        assert!(lines[ranges[1].0 - 1].starts_with("// sum: int(const double *, int)"));
        assert_eq!(cpp_type(&sigs[0]), "double(double, int)");
    }

    #[test]
    fn dependency_files_are_read_with_escaped_spaces_and_continuations() {
        let d = "w.so: /a/w.cpp /b/my\\ phys.hpp \\\n /c/x.h\n";
        assert_eq!(deps_of(d), vec![PathBuf::from("/a/w.cpp"), PathBuf::from("/b/my phys.hpp"), PathBuf::from("/c/x.h")]);
    }
}
