//! `import cpp` (spec C4, DECISIONS D290): C++ functions through a generated `extern "C"` wrapper.
//!
//! ```text
//! import cpp "libphys.so" header "phys.hpp":
//!     phys::kinetic_energy(m [kg], v [m/s]) -> [J]
//!     phys::energy(m [kg]) -> [J] as rest_energy            # one overload of phys::energy …
//!     phys::energy(m [kg], v [m/s]) -> [J] as total_energy  # … and another
//!     phys::Particle::compton_wavelength(m [kg]) -> [m]     # a static member function
//! ```
//!
//! For each signature Fermium writes a small C function into one C++ file: it takes the parameters as C types
//! (`double` for a number, `int` for `: int` and `len(…)`, a pointer to doubles for `: list`), picks the C++
//! function by converting `&phys::energy` to the function-pointer type the signature declares (so the declared
//! signature chooses among overloads, exactly, and deduces a function template's arguments), calls it inside a
//! `try` (an exception must not unwind into Fermium: its message is kept for `fermium_cpp_error`), and returns
//! the result. The file is compiled with the system's C++ compiler (`$CXX`, else c++, g++, clang++) into a shared
//! library linked against the program's library, cached by the hash of its source in Fermium's cache folder
//! (`$FERMIUM_CACHE_DIR/cpp`, else `$XDG_CACHE_HOME/fermium/cpp`, else `~/.cache/fermium/cpp`), and made again
//! when a header it includes or the library is newer than it. From there on a C++ function is a C function of
//! the wrapper, called by C3's machinery (cinterop.rs), units checked at every call.
use std::path::{Path, PathBuf};
use std::process::Command;

use fermium_syntax::ast as A;

/// A signature as the wrapper needs it: the qualified C++ name in ASCII, the parameter kinds and the result.
pub struct CppSig {
    pub qual: String,
    pub params: Vec<A::CParamKind>,
    pub rint: bool,
}

/// Why a wrapper couldn't be made: the message, its hint, and the signature it is about (None: the import line).
#[derive(Debug)]
pub struct CppError {
    pub sig: Option<usize>,
    pub msg: String,
    pub hint: Option<String>,
}

fn cerr(sig: Option<usize>, msg: impl Into<String>, hint: Option<String>) -> CppError {
    CppError { sig, msg: msg.into(), hint }
}

/// The C type of a parameter; `mutable` spells a list as `double *` instead of `const double *`.
fn ctype(k: &A::CParamKind, mutable: bool) -> &'static str {
    match k {
        A::CParamKind::Num(_) => "double",
        A::CParamKind::Int | A::CParamKind::Len(_) => "int",
        A::CParamKind::List(_) => {
            if mutable {
                "double *"
            } else {
                "const double *"
            }
        }
    }
}

/// `double(double, int)`: the C++ type a signature asks for (lists as `const double *`), for messages.
pub fn cpp_type(sig: &CppSig) -> String {
    let ps: Vec<&str> = sig.params.iter().map(|p| ctype(p, false)).collect();
    format!("{}({})", if sig.rint { "int" } else { "double" }, ps.join(", "))
}

/// The symbol of signature k's C function in the wrapper.
pub fn wrapper_symbol(k: usize) -> String {
    format!("fermium_cpp_{k}")
}

/// The wrapper's C++ source, and the lines (1-based, inclusive) each signature's code spans.
pub fn wrapper_source(include: &str, sigs: &[CppSig]) -> (String, Vec<(usize, usize)>, usize) {
    let mut out: Vec<String> = vec![
        "// Generated by Fermium for  import cpp  (C4, DECISIONS D290); it is made again when it changes.".into(),
        "#include <cstdio>".into(),
        "#include <cstring>".into(),
        "#include <exception>".into(),
    ];
    let quoted = include.replace('\\', "\\\\").replace('"', "\\\"");
    out.push(format!("#include \"{quoted}\""));
    let include_line = out.len();
    out.extend(
        r#"
static thread_local char fermium_cpp_msg[512];

static void fermium_cpp_threw(const char *f, const char *what) {
    if (what && *what)
        std::snprintf(fermium_cpp_msg, sizeof fermium_cpp_msg, "the C++ function %s threw an exception: %s", f, what);
    else
        std::snprintf(fermium_cpp_msg, sizeof fermium_cpp_msg, "the C++ function %s threw an exception", f);
}

// the message of the exception the last call threw (0: none), cleared
extern "C" int fermium_cpp_error(char *buf, int n) {
    int len = (int)std::strlen(fermium_cpp_msg);
    if (len == 0 || n <= 0) return 0;
    if (len > n - 1) len = n - 1;
    std::memcpy(buf, fermium_cpp_msg, len);
    buf[len] = 0;
    fermium_cpp_msg[0] = 0;
    return len;
}"#
        .lines()
        .map(str::to_string),
    );
    let mut ranges = vec![];
    for (k, s) in sigs.iter().enumerate() {
        out.push(String::new());
        let first = out.len() + 1;
        let ret = if s.rint { "int" } else { "double" };
        let names: Vec<String> = (0..s.params.len()).map(|j| format!("a{j}")).collect();
        let decl: Vec<String> = s.params.iter().zip(&names).map(|(p, n)| format!("{} {n}", ctype(p, true))).collect();
        let lists: Vec<usize> = (0..s.params.len()).filter(|&j| matches!(s.params[j], A::CParamKind::List(_))).collect();
        // one helper per spelling of the lists (const double * or double *): converting &f to the helper's
        // parameter picks the overload with exactly these parameter types
        let variants = if lists.len() <= 3 { 1usize << lists.len() } else { 1 };
        out.push(format!("// {}: {}", s.qual, cpp_type(s)));
        for v in 0..variants {
            let types: Vec<&str> = s.params.iter().enumerate()
                .map(|(j, p)| ctype(p, lists.iter().position(|&l| l == j).is_some_and(|b| v >> b & 1 == 1)))
                .collect();
            let mut hp = vec![format!("{ret} (*f)({})", types.join(", "))];
            hp.extend(decl.iter().cloned());
            out.push(format!("static inline {ret} fermium_cpp_call_{k}({}) {{ return f({}); }}", hp.join(", "),
                             names.join(", ")));
        }
        let mut cargs = vec![format!("&{}", s.qual)];
        cargs.extend(names.iter().cloned());
        out.push(format!("extern \"C\" {ret} {}({}) {{", wrapper_symbol(k), decl.join(", ")));
        out.push("    try {".into());
        out.push(format!("        return fermium_cpp_call_{k}({});", cargs.join(", ")));
        out.push("    } catch (const std::exception &e) {".into());
        out.push(format!("        fermium_cpp_threw(\"{}\", e.what());", s.qual));
        out.push("    } catch (...) {".into());
        out.push(format!("        fermium_cpp_threw(\"{}\", nullptr);", s.qual));
        out.push("    }".into());
        out.push("    return 0;".into());
        out.push("}".into());
        ranges.push((first, out.len()));
    }
    let mut src = out.join("\n");
    src.push('\n');
    (src, ranges, include_line)
}

/// 64-bit FNV-1a: the cache key (not a security boundary; the cache is the user's own folder).
fn fnv1a(parts: &[&[u8]]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for p in parts {
        for b in p.iter().chain(b"\x00") {
            h ^= *b as u64;
            h = h.wrapping_mul(0x100000001b3);
        }
    }
    h
}

/// Where compiled wrappers are kept.
pub fn cache_dir() -> PathBuf {
    cache_root().join("cpp")
}

/// Fermium's cache folder: `$FERMIUM_CACHE_DIR`, else `$XDG_CACHE_HOME/fermium`, else `~/.cache/fermium`
/// (`~/Library/Caches/fermium` on macOS). C++ wrappers go in `cpp/`, compiled programs in `jit/` (D317).
pub fn cache_root() -> PathBuf {
    let env = |k: &str| std::env::var(k).ok().filter(|v| !v.is_empty());
    if let Some(d) = env("FERMIUM_CACHE_DIR") {
        return PathBuf::from(d);
    }
    if let Some(d) = env("XDG_CACHE_HOME") {
        return PathBuf::from(d).join("fermium");
    }
    if let Some(h) = env("HOME") {
        if cfg!(target_os = "macos") {
            return PathBuf::from(h).join("Library/Caches/fermium");
        }
        return PathBuf::from(h).join(".cache/fermium");
    }
    std::env::temp_dir().join("fermium-cache")
}

fn mtime(p: &Path) -> Option<std::time::SystemTime> {
    std::fs::metadata(p).and_then(|m| m.modified()).ok()
}

/// The files a make-style dependency file (`-MMD`) lists.
fn deps_of(d: &str) -> Vec<PathBuf> {
    let joined = d.replace("\\\n", " ");
    let Some((_, rest)) = joined.split_once(": ") else { return vec![] };
    let mut out = vec![];
    let mut cur = String::new();
    let mut it = rest.chars().peekable();
    while let Some(c) = it.next() {
        match c {
            '\\' if it.peek() == Some(&' ') => {
                cur.push(' ');
                it.next();
            }
            ' ' | '\n' | '\t' => {
                if !cur.is_empty() {
                    out.push(PathBuf::from(std::mem::take(&mut cur)));
                }
            }
            c => cur.push(c),
        }
    }
    if !cur.is_empty() {
        out.push(PathBuf::from(cur));
    }
    out
}

/// A cached wrapper is good when it exists and nothing it was built from (its dependency file's list, and the
/// library) is newer.
fn cache_ok(so: &Path, d: &Path, lib: Option<&Path>) -> bool {
    let (Some(t), Ok(deps)) = (mtime(so), std::fs::read_to_string(d)) else { return false };
    let deps = deps_of(&deps);
    !deps.is_empty() && deps.iter().map(PathBuf::as_path).chain(lib).all(|p| mtime(p).is_some_and(|m| m <= t))
}

/// The C++ compiler: `$CXX` (which may carry arguments, like `ccache g++`), else the first of c++, g++, clang++
/// that runs.
fn find_cxx() -> Option<Vec<String>> {
    if let Some(c) = std::env::var("CXX").ok().filter(|v| !v.trim().is_empty()) {
        return Some(c.split_whitespace().map(str::to_string).collect());
    }
    ["c++", "g++", "clang++"].iter().find(|c| {
        Command::new(c).arg("--version").output().map(|o| o.status.success()).unwrap_or(false)
    }).map(|c| vec![c.to_string()])
}

/// Everything a wrapper is made from.
pub struct CppImport<'a> {
    /// the library as written ("" for a header-only import) and its path (absolute when it is a file)
    pub lib: &'a str,
    pub lib_path: &'a str,
    /// the header as written, and what the wrapper includes (an absolute path when the program's folder has it)
    pub header: &'a str,
    pub include: String,
    /// the program's folder (on the include path)
    pub base: &'a str,
    pub sigs: Vec<CppSig>,
}

/// The wrapper's path, compiled now unless the cache has it.
pub fn build_wrapper(imp: &CppImport) -> Result<String, CppError> {
    let (src, ranges, include_line) = wrapper_source(&imp.include, &imp.sigs);
    let cxx_env = std::env::var("CXX").unwrap_or_default();
    let flags = std::env::var("CXXFLAGS").unwrap_or_default();
    let header_text = std::fs::read(&imp.include).unwrap_or_default();
    let key = fnv1a(&[b"fermium-cpp-1", cxx_env.as_bytes(), flags.as_bytes(), imp.lib_path.as_bytes(), src.as_bytes(),
                      &header_text]);
    let dir = cache_dir();
    let stem = format!("w{key:016x}");
    let so = dir.join(format!("{stem}.so"));
    let dfile = dir.join(format!("{stem}.d"));
    let lib_file = Some(Path::new(imp.lib_path)).filter(|p| !imp.lib.is_empty() && p.is_absolute());
    if cache_ok(&so, &dfile, lib_file) {
        return Ok(so.to_string_lossy().into_owned());
    }
    if let Err(e) = std::fs::create_dir_all(&dir) {
        return Err(cerr(None, format!("can't make the folder for compiled C++ wrappers {}: {e}", dir.display()),
                        Some("set FERMIUM_CACHE_DIR to a folder you can write".into())));
    }
    let Some(cxx) = find_cxx() else {
        return Err(cerr(None, "import cpp needs a C++ compiler, and none was found (tried c++, g++ and clang++)",
                        Some("install one (like  sudo apt install g++), or set CXX to its path".into())));
    };
    let pid = std::process::id();
    let cpp = dir.join(format!("{stem}.cpp"));
    let tmp_cpp = dir.join(format!("{stem}.{pid}.cpp.tmp"));
    let tmp_so = dir.join(format!("{stem}.{pid}.so.tmp"));
    let tmp_d = dir.join(format!("{stem}.{pid}.d.tmp"));
    let log = dir.join(format!("{stem}.log"));
    let write = std::fs::write(&tmp_cpp, &src).and_then(|_| std::fs::rename(&tmp_cpp, &cpp));
    if let Err(e) = write {
        return Err(cerr(None, format!("can't write the C++ wrapper {}: {e}", cpp.display()), None));
    }
    let mut cmd = Command::new(&cxx[0]);
    cmd.args(&cxx[1..]).args(["-x", "c++", "-std=c++17", "-O2", "-fPIC", "-shared", "-MMD", "-MF"]).arg(&tmp_d)
        .arg("-I").arg(imp.base);
    if let Some(parent) = Path::new(&imp.include).parent().filter(|p| p.is_absolute()) {
        cmd.arg("-I").arg(parent);
    }
    cmd.arg("-o").arg(&tmp_so).arg(&cpp).args(["-x", "none"]);
    if !imp.lib.is_empty() {
        let lp = Path::new(imp.lib_path);
        if lp.is_absolute() {
            cmd.arg(lp);
            if let Some(parent) = lp.parent() {
                cmd.arg(format!("-Wl,-rpath,{}", parent.display()));
            }
        } else {
            cmd.arg(format!("-l:{}", imp.lib_path));
        }
    }
    if cfg!(target_os = "linux") {
        cmd.arg("-Wl,--no-undefined");
    }
    cmd.args(flags.split_whitespace());
    let out = match cmd.output() {
        Ok(o) => o,
        Err(e) => {
            return Err(cerr(None, format!("can't run the C++ compiler {}: {e}", cxx[0]),
                            Some("set CXX to a C++ compiler's path".into())));
        }
    };
    let stderr = String::from_utf8_lossy(&out.stderr).into_owned();
    if !out.status.success() {
        let _ = std::fs::write(&log, format!("{:?}\n\n{stderr}", cmd));
        let _ = std::fs::remove_file(&tmp_so);
        let _ = std::fs::remove_file(&tmp_d);
        return Err(summarise(&stderr, imp, &cpp, &ranges, include_line, &log));
    }
    let moved = std::fs::rename(&tmp_d, &dfile).and_then(|_| std::fs::rename(&tmp_so, &so));
    if let Err(e) = moved {
        return Err(cerr(None, format!("can't store the compiled C++ wrapper in {}: {e}", dir.display()), None));
    }
    Ok(so.to_string_lossy().into_owned())
}

/// The compiler's complaint in one line, about the signature it concerns.
fn summarise(stderr: &str, imp: &CppImport, cpp: &Path, ranges: &[(usize, usize)], include_line: usize, log: &Path)
             -> CppError {
    let full = Some(format!("the compiler's full output is in {}", log.display()));
    let mapping = "Fermium passes a number ([unit] or plain) as double, : int and len(…) as int and : list as const \
                   double * (or double *), and expects double back (-> [unit], -> number) or int (-> int)";
    let cpp_s = cpp.to_string_lossy();
    for line in stderr.lines() {
        // link errors (GNU ld, lld, macOS ld)
        let undefined = line.split_once("undefined reference to `").map(|x| x.1.trim_end_matches('\''))
            .or_else(|| line.split_once("undefined symbol: ").map(|x| x.1.trim()));
        if let Some(sym) = undefined {
            let sig = imp.sigs.iter().position(|s| sym.starts_with(&format!("{}(", s.qual)) || sym == s.qual);
            return if imp.lib.is_empty() {
                cerr(sig, format!("{sym} is declared in {} but defined nowhere: the import names no library",
                                  imp.header),
                     Some(format!("name the library before the header, like  import cpp \"libfoo.so\" header \"{}\"",
                                  imp.header)))
            } else {
                cerr(sig, format!("the C++ library {} has no definition of {sym}", imp.lib),
                     Some(format!("the header declares it: check that the library is built from the same sources \
                                   (nm -DC {} lists the functions it defines)", imp.lib)))
            };
        }
        let Some((at, msg)) = line.split_once(": fatal error: ").or_else(|| line.split_once(": error: ")) else {
            continue;
        };
        let msg = msg.trim();
        let mut parts = at.rsplitn(3, ':').collect::<Vec<_>>();
        parts.reverse();
        // file:line:col, file:line, or a tool's name (a link error without a location)
        let (file, lno) = match parts.as_slice() {
            [f, l, c] if l.parse::<usize>().is_ok() && c.parse::<usize>().is_ok() => (f.to_string(), l.parse().unwrap()),
            [f, l, c] if c.parse::<usize>().is_ok() => (format!("{f}:{l}"), c.parse().unwrap()),
            [f, l] if l.parse::<usize>().is_ok() => (f.to_string(), l.parse().unwrap()),
            _ => (String::new(), 0usize),
        };
        if file.is_empty() {
            continue;
        }
        if file == cpp_s {
            if lno == include_line || msg.contains("No such file") || msg.contains("file not found") {
                return cerr(None, format!("can't find the header {}", imp.header),
                            Some("the path is relative to the program's folder".into()));
            }
            let Some(k) = ranges.iter().position(|&(a, b)| (a..=b).contains(&lno)) else {
                return cerr(None, format!("the C++ wrapper didn't compile: {msg}"), full);
            };
            let s = &imp.sigs[k];
            let has = |ws: &[&str]| ws.iter().any(|w| msg.contains(w));
            if has(&["is not a member of", "no member named", "was not declared", "undeclared identifier",
                     "has not been declared", "does not name", "is not a class, namespace", "not a class or namespace"]) {
                return cerr(Some(k), format!("the header {} declares no function {}", imp.header, s.qual),
                            Some("check the spelling and the namespace (C++ names are case-sensitive)".into()));
            }
            // a non-static member function: &Class::f is a pointer to member
            if stderr.contains("::*)") {
                return cerr(Some(k), format!("{} is a member function, which needs an object; only free functions and \
                                              static member functions can be imported", s.qual),
                            Some("add a free (or static) function to the library that makes the object and calls it"
                                .into()));
            }
            if has(&["ambiguous"]) {
                return cerr(Some(k), format!("more than one overload of {} has the C++ type {}", s.qual, cpp_type(s)),
                            Some(mapping.into()));
            }
            if has(&["no matching function", "invalid conversion", "no known conversion", "cannot initialize",
                     "no matches converting", "overloaded function", "cannot convert", "invalid static_cast"]) {
                return cerr(Some(k), format!("no overload of {} has the C++ type {}", s.qual, cpp_type(s)),
                            Some(mapping.into()));
            }
            return cerr(Some(k), format!("the C++ wrapper for {} didn't compile: {msg}", s.qual), full);
        }
        let shown = Path::new(&file).file_name().map(|f| f.to_string_lossy().into_owned()).unwrap_or(file.clone());
        return cerr(None, format!("the header {} doesn't compile: {shown}, line {lno}: {msg}", imp.header), full);
    }
    let first = stderr.lines().map(str::trim).find(|l| !l.is_empty()).unwrap_or("no message");
    cerr(None, format!("compiling the C++ wrapper failed: {first}"), full)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_wrapper_picks_the_declared_overload_through_a_function_pointer() {
        let sigs = vec![
            CppSig { qual: "phys::energy".into(), params: vec![A::CParamKind::Num(None), A::CParamKind::Int], rint: false },
            CppSig { qual: "sum".into(), params: vec![A::CParamKind::List(None), A::CParamKind::Len("x".into())],
                     rint: true },
        ];
        let (src, ranges, inc) = wrapper_source("/x/phys.hpp", &sigs);
        let lines: Vec<&str> = src.lines().collect();
        assert_eq!(lines[inc - 1], "#include \"/x/phys.hpp\"");
        assert!(src.contains("static inline double fermium_cpp_call_0(double (*f)(double, int), double a0, int a1) \
                              { return f(a0, a1); }"), "{src}");
        assert!(src.contains("return fermium_cpp_call_0(&phys::energy, a0, a1);"), "{src}");
        // a list may be const double * or double * in the C++ function
        assert!(src.contains("int (*f)(const double *, int)") && src.contains("int (*f)(double *, int)"), "{src}");
        assert!(src.contains("extern \"C\" int fermium_cpp_1(double * a0, int a1) {"), "{src}");
        assert_eq!(ranges.len(), 2);
        assert!(lines[ranges[1].0 - 1].starts_with("// sum: int(const double *, int)"));
        assert_eq!(cpp_type(&sigs[0]), "double(double, int)");
    }

    #[test]
    fn dependency_files_are_read_with_escaped_spaces_and_continuations() {
        let d = "w.so: /a/w.cpp /b/my\\ phys.hpp \\\n /c/x.h\n";
        assert_eq!(deps_of(d), vec![PathBuf::from("/a/w.cpp"), PathBuf::from("/b/my phys.hpp"), PathBuf::from("/c/x.h")]);
    }
}
