#!/usr/bin/env python3
"""Generate rust/crates/fermium-runtime/src/plot/font_data.rs: the glyph outlines of a subset of DejaVu Sans
(the font matplotlib uses, so v2's plots look like v1's) for the native PNG/GIF rasterizer.

Developer tooling only (uses matplotlib's font reader); the generated Rust file is committed. DejaVu Sans:
Bitstream Vera license (redistribution allowed with the notice, reproduced in the generated file); DejaVu
changes are public domain.

Run from the repository root:  python3 rust/tools/font_subset.py
"""
import os

from matplotlib.font_manager import FontProperties
from matplotlib.ft2font import FT2Font
from matplotlib.textpath import TextPath
import matplotlib

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TTF = os.path.join(os.path.dirname(matplotlib.__file__), "mpl-data", "fonts", "ttf", "DejaVuSans.ttf")
OUT = os.path.join(ROOT, "rust", "crates", "fermium-runtime", "src", "plot", "font_data.rs")

CHARS = "".join(chr(c) for c in range(32, 127))
CHARS += "αβγδεζηθικλμνξοπρςστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩϕϑϵ"
CHARS += "⁰¹²³⁴⁵⁶⁷⁸⁹⁻⁺⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₋₊ₑ"
CHARS += "°′″·×÷−±√∂∇∫ħℏÅµ≤≥≈≠∞⊙☉→←↑↓…½¼¾ʹ‰§©®™€£¥¢ÄÖÜäöüßéèêàâçñåøæœ∑∏∆Ω√∛∝∈∼⟨⟩|‖"
LICENSE = open(os.path.join(os.path.dirname(TTF), "LICENSE_DEJAVU")).read()


def main():
    fp = FontProperties(fname=TTF)
    ft = FT2Font(TTF)
    ft.set_size(2048, 72)
    upem = ft.units_per_EM
    rows = []
    seen = set()
    for ch in CHARS:
        if ch in seen:
            continue
        seen.add(ch)
        if ft.get_char_index(ord(ch)) == 0:
            continue
        g = ft.load_char(ord(ch))
        adv = int(round(g.linearHoriAdvance / 65536 * upem / 2048))
        data = []
        if ch != " ":
            p = TextPath((0, 0), ch, size=upem, prop=fp)
            v, c = p.vertices, p.codes
            i = 0
            while i < len(c):
                code = int(c[i])
                if code == 1:
                    data += [1, round(v[i][0]), round(v[i][1])]
                    i += 1
                elif code == 2:
                    data += [2, round(v[i][0]), round(v[i][1])]
                    i += 1
                elif code == 3:
                    data += [3, round(v[i][0]), round(v[i][1]), round(v[i + 1][0]), round(v[i + 1][1])]
                    i += 2
                elif code == 4:   # cubic (not in TrueType fonts): approximate by its end point
                    data += [2, round(v[i + 2][0]), round(v[i + 2][1])]
                    i += 3
                else:
                    data += [0]
                    i += 1
        rows.append((ch, adv, data))
    with open(OUT, "w") as fh:
        fh.write("//! Glyph outlines of a subset of DejaVu Sans, generated by rust/tools/font_subset.py; do not edit.\n")
        fh.write("//! Commands in font units (y up): 1 x y = move, 2 x y = line, 3 cx cy x y = quadratic, 0 = close.\n//!\n")
        for line in LICENSE.splitlines():
            fh.write("//! " + line + "\n")
        fh.write("\n#![allow(dead_code)]\n")
        fh.write(f"\npub const UNITS_PER_EM: f64 = {upem}.0;\npub const ASCENDER: f64 = {ft.ascender}.0;\n")
        fh.write(f"pub const DESCENDER: f64 = {ft.descender}.0;\n\n")
        fh.write("/// (character, advance, outline commands), sorted by character\n")
        fh.write("pub static GLYPHS: &[(char, u16, &[i16])] = &[\n")
        for ch, adv, data in sorted(rows, key=lambda r: r[0]):
            esc = "\\\\" if ch == "\\" else "\\'" if ch == "'" else ch
            fh.write(f"    ('{esc}', {adv}, &[{', '.join(str(int(d)) for d in data)}]),\n")
        fh.write("];\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(rows)} glyphs, {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    main()
