#!/usr/bin/env python3
"""Generate rust/crates/fermium-syntax/src/tables.rs from Fermium 1.5 (the oracle).

The Rust lexer and parser need a few facts the Python implementation takes from Python itself or from other
modules: which characters Python's str.isalpha() / str.isalnum() accept (Unicode 14 as in Python 3.11), the unit
names (fermium/units.py) with the description of their dimension used in the A1 messages, and the names of the
built-in constants (fermium/constants.py).  Run from the repository root:

    python3 rust/tools/gen_syntax_tables.py > rust/crates/fermium-syntax/src/tables.rs
    python3 rust/tools/gen_syntax_tables.py --names > rust/crates/fermium-syntax/src/char_names.rs
"""
import os
import sys
import unicodedata

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

from fermium import units as U            # noqa: E402
from fermium.constants import CONSTANTS   # noqa: E402


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(chr(cp))
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def rs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_ranges(name, rr):
    print(f"pub static {name}: &[(u32, u32)] = &[")
    line = "   "
    for a, b in rr:
        item = f" (0x{a:X}, 0x{b:X}),"
        if len(line) + len(item) > 116:
            print(line)
            line = "   "
        line += item
    print(line)
    print("];\n")


def names_of_non_letters():
    """unicodedata.name(ch).title() for every named character that is not a letter (the lexer names those in
    'unexpected character' errors; letters always start a name).  Algorithmic names are left out."""
    out = []
    for cp in range(0x110000):
        ch = chr(cp)
        if ch.isalpha():
            continue
        n = unicodedata.name(ch, None)
        if n is None:
            continue
        out.append((cp, n.title()))
    return out


print("// @generated by rust/tools/gen_syntax_tables.py from Fermium 1.5 (Python "
      f"{sys.version.split()[0]}, Unicode {unicodedata.unidata_version}). Do not edit.\n")
if "--names" in sys.argv:
    print("/// unicodedata.name(ch).title() of the characters that aren't letters (sorted by code point).")
    print("pub static CHAR_NAMES: &[(u32, &str)] = &[")
    for cp, n in names_of_non_letters():
        print(f"    (0x{cp:X}, {rs(n)}),")
    print("];")
    sys.exit(0)
emit_ranges("PY_ALPHA", ranges(str.isalpha))
emit_ranges("PY_ALNUM", ranges(str.isalnum))
emit_ranges("PY_DIGIT", ranges(str.isdigit))

print("/// Unit names of fermium/units.py: (name, takes SI prefixes, what it measures for the A1 messages).")
print("pub static UNITS: &[(&str, bool, &str)] = &[")
for name, (_, dim, pref) in U._UNITS.items():
    what = U.dim_name(dim).split(" [")[0]
    print(f"    ({rs(name)}, {'true' if pref else 'false'}, {rs(what)}),")
print("];\n")
print("/// Affine temperature units (°C, °F) and what they measure.")
print("pub static AFFINE: &[(&str, &str)] = &[")
for name in U._AFFINE:
    print(f"    ({rs(name)}, {rs(U.dim_name(U.TH).split(' [')[0])}),")
print("];\n")
print("/// SI prefixes, in the order of fermium/units.py.")
print("pub static PREFIXES: &[&str] = &[" + ", ".join(rs(p) for p in U.PREFIXES) + "];\n")
print("pub static PREFIX_2022: &[&str] = &[" + ", ".join(rs(p) for p in sorted(U._PREFIX_2022)) + "];")
print("pub static ALLOWED_2022: &[&str] = &[" + ", ".join(rs(p) for p in sorted(U._ALLOWED_2022)) + "];")
print("pub static BLOCKED: &[&str] = &[" + ", ".join(rs(p) for p in sorted(U._BLOCKED)) + "];\n")
names = sorted(set(CONSTANTS) | {a for v in CONSTANTS.values() for a in v[3]})
print("/// Built-in constants and their aliases (fermium/constants.py).")
print("pub static CONSTANT_NAMES: &[&str] = &[" + ", ".join(rs(n) for n in names) + "];\n")
