#!/usr/bin/env python3
"""Generate the reference fixtures for fermium-runtime's native numerics (spec §B6).

Python (Fermium 1.5 = the oracle, plus SciPy/NumPy where v1 called them) is used HERE ONLY, to write
plain-text fixtures under rust/crates/fermium-runtime/tests/fixtures/; `cargo test -p fermium-runtime`
compares the Rust results with them. Nothing at run time needs Python.

Format: one case per line, `name value value ...`, floats as Python repr (shortest round trip), or
`name ERR kind a b` for a v1 run-time error. Lines starting with # are comments.

Run from the repository root:  python3 rust/tools/numerics_fixtures.py [section ...]
"""
from __future__ import annotations

import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "rust", "crates", "fermium-runtime", "tests", "fixtures")

inf = math.inf


def r(x):
    return repr(float(x))


class Writer:
    def __init__(self, name, header):
        self.path = os.path.join(OUT, name)
        self.lines = [f"# {line}" for line in header.strip().splitlines()]
        self.lines.append("# generated by rust/tools/numerics_fixtures.py; do not edit")

    def row(self, name, *vals):
        self.lines.append(" ".join([name] + [v if isinstance(v, str) else r(v) for v in vals]))

    def close(self):
        os.makedirs(OUT, exist_ok=True)
        with open(self.path, "w") as fh:
            fh.write("\n".join(self.lines) + "\n")
        print(f"wrote {os.path.relpath(self.path, ROOT)} ({len(self.lines)} lines)")


# --------------------------------------------------------------------------------------- quadrature
# The same integrands are defined in rust/crates/fermium-runtime/tests/quad.rs (by name).
# Squares and cubes are written as products: Python's x ** 2 calls libm pow, which is not always
# correctly rounded, while Rust (LLVM) turns powf(x, 2.0) into x * x.
from math import sin, cos, sqrt, log, atan, tanh, pi  # noqa: E402


def exp(x):
    """IEEE exp, as the compiled code and Rust: overflow gives inf, not OverflowError."""
    try:
        return math.exp(x)
    except OverflowError:
        return math.inf

QUAD_CASES = [
    # name, f, a, b, truth (None: v1's value is right)
    ("poly", lambda x: x * x, 0.0, 3.0, 9.0),
    ("gauss_inf", lambda x: exp(-x * x), -inf, inf, sqrt(pi)),
    ("inv_sqrt", lambda x: 1 / sqrt(x), 0.0, 1.0, 2.0),
    ("planck", lambda x: x * x * x / (exp(x) - 1), 0.0, inf, pi ** 4 / 15),
    ("sinc", lambda x: sin(x) / x, 0.0, 10.0, None),
    ("decay", lambda x: exp(-x / 2.5), 0.0, inf, 2.5),
    ("lorentz", lambda x: 1 / (1 + x * x), -inf, inf, pi),
    ("log", lambda x: log(x), 0.0, 1.0, -1.0),
    ("damped_cos", lambda x: cos(30 * x) * exp(-x), 0.0, 5.0, None),
    ("reversed", lambda x: x * x * x, 2.0, -1.0, -3.75),
    ("left_tail", lambda x: exp(x), -inf, 0.0, 1.0),
    ("power_tail", lambda x: 1 / ((1 + x) * (1 + x)), 0.0, inf, 1.0),
    ("kink", lambda x: abs(x - 0.3), 0.0, 1.0, 0.29),
    ("step", lambda x: 1.0 if x < 0.37 else 2.0, 0.0, 1.0, 1.63),
    ("sqrt_sing_mid", lambda x: 1 / sqrt(abs(x - 0.5)), 0.0, 1.0, 4 * sqrt(0.5)),
    ("atan_tail", lambda x: atan(x) / (1 + x * x * x), 0.0, inf, None),
    ("tiny_scale", lambda x: exp(-x / 1e-15), 0.0, inf, 1e-15),
    ("huge_scale", lambda x: exp(-x / 1e20), 0.0, inf, 1e20),
    ("tanh_wall", lambda x: tanh(1000 * (x - 0.123)), 0.0, 1.0, None),
    ("x_sin_inf", lambda x: x * exp(-x) * sin(x), 0.0, inf, 0.5),
    ("gauss_offset", lambda x: exp(-(x - 7.3) * (x - 7.3)), -inf, inf, sqrt(pi)),
    ("zero", lambda x: 0.0 * x, 0.0, 1.0, 0.0),
    ("x_pow_m09", lambda x: x ** -0.9, 0.0, 1.0, 10.0),
    ("nested_scale", lambda x: exp(-x * x / 2e-6), -1.0, 1.0, sqrt(2e-6 * pi)),
    # v1's documented failures (OPEN_ITEMS RT1-1, BL-1, BL-2, BL-3) and errors
    ("rt1_1", lambda x: exp(-((x - 1) / 1e-6) * ((x - 1) / 1e-6)), 0.0, inf, 1e-6 * sqrt(pi)),
    ("bl1", lambda x: exp(-(x - 1000) * (x - 1000) * 100), 0.0, 2000.0, sqrt(pi / 100)),
    ("bl2", lambda x: exp(-x * x), -1e6, 1e6, sqrt(pi)),
    ("bl3_06", lambda x: abs(x - 0.3) ** -0.6, 0.0, 1.0, (0.3 ** 0.4 + 0.7 ** 0.4) / 0.4),
    ("bl3_08", lambda x: abs(x - 0.3) ** -0.8, 0.0, 1.0, (0.3 ** 0.2 + 0.7 ** 0.2) / 0.2),
    ("recip", lambda x: 1 / x, 0.0, 1.0, None),
    ("sin_inf", lambda x: sin(x), 0.0, inf, None),
]


def safe(f):
    def g(x):
        try:
            return f(x)
        except ZeroDivisionError:
            return math.inf
        except (ValueError, OverflowError):
            return math.nan
    return g


def gen_quad():
    from fermium.interp import quad, _Fail
    w = Writer("quad.txt", """
v1's adaptive Gauss-Kronrod (fermium.interp.quad, which mirrors the compiled fm_quad), rtol 1e-10.
name  v1_value all_zero truth   |   name ERR kind a b truth   (truth: nan when v1's value is right)""")
    for name, f, a, b, truth in QUAD_CASES:
        t = math.nan if truth is None else truth
        zero = []
        try:
            v = quad(safe(f), a, b, warn=lambda: zero.append(1))
            w.row(name, v, 1.0 if zero else 0.0, t)
        except _Fail as fl:
            w.row(name, "ERR", str(fl.kind), fl.a, fl.b, t)
    w.close()


# --------------------------------------------------------------------------------------- ODEs (explicit)
# The same right-hand sides are in rust/crates/fermium-runtime/tests/ode.rs (by name).
def _vdp(t, y):
    return [y[1], 5.0 * (1 - y[0] * y[0]) * y[1] - y[0]]


def _kepler(t, y):
    r3 = (y[0] * y[0] + y[1] * y[1]) ** 1.5
    return [y[2], y[3], -y[0] / r3, -y[1] / r3]


def _lorenz(t, y):
    return [10.0 * (y[1] - y[0]), y[0] * (28.0 - y[2]) - y[1], y[0] * y[1] - 8.0 / 3.0 * y[2]]


ODE_CASES = [
    # name, method, f, y0, t0, t1, rtol or step, event, tdep, atol
    ("decay6", "rk45", lambda t, y: [-y[0]], [1.0], 0.0, 5.0, 1e-6, None, False, None),
    ("decay10", "rk45", lambda t, y: [-y[0]], [1.0], 0.0, 5.0, 1e-10, None, False, None),
    ("harmonic", "rk45", lambda t, y: [y[1], -4.0 * y[0]], [1.0, 0.0], 0.0, 20.0, 1e-8, None, False, None),
    ("vdp", "rk45", _vdp, [2.0, 0.0], 0.0, 20.0, 1e-8, None, False, None),
    ("kepler", "rk45", _kepler, [0.5, 0.0, 0.0, sqrt(3.0)], 0.0, 2 * pi, 1e-10, None, False, None),
    ("backwards", "rk45", lambda t, y: [t * y[0]], [1.0], 2.0, 0.0, 1e-8, None, False, None),
    ("lorenz", "rk45", _lorenz, [1.0, 1.0, 1.0], 0.0, 10.0, 1e-9, None, False, None),
    ("projectile", "rk45", lambda t, y: [y[1], -9.81], [0.0, 20.0], 0.0, 100.0, 1e-8,
     lambda t, y: [y[0]], False, None),
    ("jump", "rk45", lambda t, y: [1.0 if t < 0.3 else -2.0], [0.0], 0.0, 1.0, 1e-8, None, True, None),
    ("atol", "rk45", lambda t, y: [-y[0] + 1e-20 * cos(t)], [1e-20], 0.0, 10.0, 1e-6, None, False, [1e-24]),
    ("stiffish", "rk45", lambda t, y: [-1e5 * (y[0] - cos(t))], [0.0], 0.0, 4.0, 1e-6, None, False, None),
    ("blowup", "rk45", lambda t, y: [y[0] * y[0]], [1.0], 0.0, 2.0, 1e-8, None, False, None),
    ("nan_start", "rk45", lambda t, y: [1.0 / t if t else math.inf], [1.0], 0.0, 1.0, 1e-8, None, False, None),
    ("no_event", "rk45", lambda t, y: [1.0], [0.0], 0.0, 1.0, 1e-8, lambda t, y: [y[0] + 1.0], False, None),
    ("rk4_harm", "rk4", lambda t, y: [y[1], -y[0]], [1.0, 0.0], 0.0, 10.0, 0.01, None, False, None),
    ("rk4_coarse", "rk4", lambda t, y: [y[1], -y[0]], [1.0, 0.0], 0.0, 30.0, 0.7, None, False, None),
    ("rk4_event", "rk4", lambda t, y: [y[1], -9.81], [0.0, 20.0], 0.0, 100.0, 0.01,
     lambda t, y: [y[0]], False, None),
    ("rk4_back", "rk4", lambda t, y: [-2.0 * y[0]], [1.0], 1.0, -1.0, 0.05, None, False, None),
]
FRACS = [0.1, 0.33, 0.5, 0.77, 0.999]


def gen_ode():
    from fermium import interp as I
    w = Writer("ode.txt", """
v1's explicit ODE solvers (fermium.interp.dp45 / rk4 + rk4_error), which mirror the compiled kernels.
name n t_last y_last... [y(t_k) y'(t_k) for comp 0 at t0 + FRACS*(t_last - t0)] max0 min0 nwarn warn_kind warn_a
or name ERR kind a b""")
    for name, method, f, y0, t0, t1, par, ev, tdep, atol in ODE_CASES:
        warns = []
        try:
            if method == "rk4":
                sol = I.rk4(f, y0, t0, t1, par, ev, -1, -1)
                est = I.rk4_error(f, sol)
                if est > I.RK4_WARN:
                    warns.append((7, est))
            else:
                sol = I.dp45(f, y0, t0, t1, par, ev, -1, -1, tdep, lambda c: warns.append((2, c)), atol)
        except I._Fail as fl:
            w.row(name, "ERR", str(fl.kind), fl.a, fl.b)
            continue
        vals = [float(sol.n), sol.t[-1]] + sol.y[-sol.dim:]
        tl = sol.t[-1]
        for fr in FRACS:
            tt = t0 + fr * (tl - t0)
            vals += [sol.eval(0, tt, False), sol.eval(0, tt, True)]
        vals += [I.Interpreter.sol_ext(sol, 0, 1.0), I.Interpreter.sol_ext(sol, 0, -1.0)]
        vals += [float(len(warns))] + (list(warns[0]) if warns else [0.0, 0.0])
        w.row(name, *vals)
    w.close()


# --------------------------------------------------------------------------------------- stiff ODEs
# v1's stiff_solve (fermium/runtime/stiff.py) over SciPy's Radau / BDF. Same cases in tests/stiff.rs.
def _robertson(t, y):
    return [-0.04 * y[0] + 1e4 * y[1] * y[2], 0.04 * y[0] - 1e4 * y[1] * y[2] - 3e7 * y[1] * y[1], 3e7 * y[1] * y[1]]


def _vdp1000(t, y):
    return [y[1], 1000.0 * (1 - y[0] * y[0]) * y[1] - y[0]]


STIFF_CASES = [
    # name, f, y0, t0, t1, rtol, event, atol
    ("robertson", _robertson, [1.0, 0.0, 0.0], 0.0, 40.0, 1e-6, None, None),
    ("robertson9", _robertson, [1.0, 0.0, 0.0], 0.0, 1e4, 1e-9, None, None),
    ("vdp1000", _vdp1000, [2.0, 0.0], 0.0, 3000.0, 1e-6, None, None),
    ("lin", lambda t, y: [-1e5 * (y[0] - cos(t))], [0.0], 0.0, 4.0, 1e-8, None, None),
    ("chain", lambda t, y: [-50.0 * y[0], 50.0 * y[0] - 0.01 * y[1], 0.01 * y[1]], [1.0, 0.0, 0.0], 0.0, 5.0,
     1e-7, None, None),
    ("event", lambda t, y: [-1000.0 * (y[0] - 1.0)], [0.0], 0.0, 1.0, 1e-8, lambda t, y: [y[0] - 0.5], None),
    ("back", lambda t, y: [20.0 * (y[0] - sin(t))], [0.0], 2.0, -1.0, 1e-8, None, None),
    ("user_atol", lambda t, y: [-y[0], y[0] - 1e3 * y[1]], [1e-12, 0.0], 0.0, 10.0, 1e-6, None, [1e-20, 1e-20]),
    ("blowup", lambda t, y: [y[0] * y[0]], [1.0], 0.0, 2.0, 1e-8, None, None),
    ("no_event", lambda t, y: [-y[0]], [1.0], 0.0, 1.0, 1e-8, lambda t, y: [y[0] + 1.0], None),
]


def gen_stiff():
    from fermium.runtime.stiff import stiff_solve, StiffFail
    from fermium import interp as I
    w = Writer("stiff.txt", """
v1's stiff solvers (fermium.runtime.stiff.stiff_solve over SciPy Radau / BDF), per method.
name/method n t_last y_last... [y(t_k) y'(t_k) comp 0 at t0 + FRACS*(t_last - t0)] max0 min0   or  name/method ERR kind a b""")
    for method in ("radau", "bdf"):
        for name, f, y0, t0, t1, rtol, ev, atol in STIFF_CASES:
            key = f"{name}/{method}"
            try:
                ts, ys, dys = stiff_solve(f, y0, t0, t1, rtol, method, ev, -1.0, -1.0, atol)
            except StiffFail as fl:
                w.row(key, "ERR", str(fl.kind), fl.a, fl.b)
                continue
            sol = I.Sol(len(y0))
            sol.t, sol.y, sol.dy = list(ts), list(ys), list(dys)
            vals = [float(sol.n), sol.t[-1]] + sol.y[-sol.dim:]
            tl = sol.t[-1]
            for fr in FRACS:
                tt = t0 + fr * (tl - t0)
                vals += [sol.eval(0, tt, False), sol.eval(0, tt, True)]
            vals += [I.Interpreter.sol_ext(sol, 0, 1.0), I.Interpreter.sol_ext(sol, 0, -1.0)]
            w.row(key, *vals)
    w.close()


# --------------------------------------------------------------------------------------- fit
# v1's least_squares_fit (fermium/runtime/fitting.py over SciPy least_squares 'lm'). The data are
# written into the fixture; the models are in tests/fit.rs (by name).
def _noise(i, amp):
    return amp * sin(12.9898 * i + 78.233 * sin(0.5 * i))


def _fit_data():
    import numpy as np
    cases = []
    x = np.array([0.5 * i for i in range(20)])
    cases.append(("line", lambda p, x: p[0] * x + p[1], x, 2.5 * x - 1.0 + np.array([_noise(i, 0.3) for i in range(20)]),
                  [None, None]))
    t = np.array([0.2 * i for i in range(30)])
    yd = 3.0 * np.exp(-t / 1.7) + np.array([_noise(i, 0.02) for i in range(30)])
    cases.append(("decay_scan", lambda p, x: p[0] * np.exp(-x / p[1]), t, yd, [None, None]))
    cases.append(("decay_guess", lambda p, x: p[0] * np.exp(-x / p[1]), t, yd, [2.0, 1.0]))
    xg = np.array([-3.0 + 0.25 * i for i in range(25)])
    yg = 4.0 * np.exp(-(xg - 0.4) ** 2 / (2 * 0.7 ** 2)) + 0.5 + np.array([_noise(i, 0.05) for i in range(25)])
    cases.append(("gauss", lambda p, x: p[0] * np.exp(-(x - p[1]) * (x - p[1]) / (2 * p[2] * p[2])) + p[3], xg, yg,
                  [None, 0.0, 1.0, None]))
    xp = np.array([1.0 + 0.5 * i for i in range(15)])
    ypw = 0.8 * xp ** 1.5 * (1 + np.array([_noise(i, 0.01) for i in range(15)]))
    cases.append(("power", lambda p, x: p[0] * x ** p[1], xp, ypw, [None, None]))
    ts = np.array([2e-7 * i for i in range(25)])
    ysi = 1.6e-19 * np.exp(-ts / 1.3e-6) * (1 + np.array([_noise(i, 0.01) for i in range(25)]))
    cases.append(("si_scale", lambda p, x: p[0] * np.exp(-x / p[1]), ts, ysi, [None, None]))
    xd = np.array([1.0 * i for i in range(8)])
    cases.append(("degenerate", lambda p, x: p[0] * p[1] * x, xd, 2.0 * xd + np.array([_noise(i, 0.1) for i in range(8)]),
                  [1.0, 1.0]))
    to = np.array([0.1 * i for i in range(60)])
    yo = 2.0 * np.exp(-to / 3.0) * np.cos(4.0 * to) + np.array([_noise(i, 0.03) for i in range(60)])
    cases.append(("damped", lambda p, x: p[0] * np.exp(-x / p[1]) * np.cos(p[2] * x), to, yo, [1.5, 2.0, 3.9]))
    xe = np.array([1.0, 2.0, 3.0, 4.0])
    cases.append(("exact", lambda p, x: p[0] * x + p[1], xe, 3.0 * xe + 2.0, [None, None]))
    xk = np.array([1.0, 2.0])
    cases.append(("n_eq_k", lambda p, x: p[0] * x + p[1], xk, np.array([1.0, 4.0]), [None, None]))
    return cases


def gen_fit():
    import numpy as np
    from fermium.runtime.fitting import least_squares_fit
    w = Writer("fit.txt", """
v1's fit: least_squares_fit (SciPy least_squares 'lm', x_scale |p0|) + covariance (fermium/runtime/fitting.py).
name:x ...   name:y ...   name:guess g...(nan = none)   name k params... errors...(nan = none) rms""")
    for name, model, x, y, guess in _fit_data():
        w.row(name + ":x", *list(x))
        w.row(name + ":y", *list(y))
        w.row(name + ":guess", *[math.nan if g is None else g for g in guess])
        best, errs, rms = least_squares_fit(lambda p: model(p, x) - y, np.zeros(len(x)), guess)
        w.row(name, float(len(guess)), *best, *[math.nan if e is None else e for e in errs], rms)
    w.close()


# --------------------------------------------------------------------------------------- roots
# v1's algebraic solve (fermium.interp.root, mirror of fm_root) and SciPy's brentq. Same functions in
# tests/roots.rs (by name): (f, scale or None, a, b).
from math import tan  # noqa: E402

ROOT_CASES = [
    ("cos_x", lambda x: cos(x) - x, lambda x: abs(cos(x)) + abs(x), 0.0, 2.0),
    ("first_of_many", lambda x: sin(x), None, 0.5, 20.0),
    ("cubic", lambda x: x * x * x - 2 * x - 5, None, 0.0, 3.0),
    ("kepler_E", lambda x: x - 0.9 * sin(x) - 1.3, None, 0.0, 3.0),
    ("at_start", lambda x: x - 1.0, None, 1.0, 2.0),
    ("on_scan_point", lambda x: x - 0.5, None, 0.0, 1.0),
    ("planck_peak", lambda x: 3 * (1 - exp(-x)) - x, None, 0.5, 10.0),
    ("tiny_scale", lambda x: x - 3.3e-19, None, 0.0, 1e-18),
    ("noise", lambda x: (1e16 + x) - 1e16 - 0.5, lambda x: abs(1e16 + x) + 1e16 + 0.5, 0.0, 3.0),
    ("no_root", lambda x: x * x + 1, None, -1.0, 1.0),
    ("pole", lambda x: tan(x), None, 1.0, 2.0),
    ("backwards", lambda x: exp(x) - 2.0, None, 3.0, 0.0),
]


def gen_roots():
    from fermium.interp import root, _Fail
    from scipy.optimize import brentq
    w = Writer("roots.txt", """
v1's solve (fermium.interp.root: first root after a, Illinois) and scipy brentq (defaults).
name x warn(nan = none) brentq(nan = n/a)   or   name ERR kind a b""")
    for name, f, scale, a, b in ROOT_CASES:
        warns = []
        try:
            x = root(f, a, b, scale=scale, warn=lambda v: warns.append(v))
        except _Fail as fl:
            w.row(name, "ERR", str(fl.kind), fl.a, fl.b)
            continue
        try:
            bq = brentq(f, a, b) if f(a) * f(b) < 0 else math.nan
        except (ValueError, RuntimeError):
            bq = math.nan
        w.row(name, x, warns[0] if warns else math.nan, bq)
    w.close()


# --------------------------------------------------------------------------------------- eigen
# v1's eigen_solve (fermium/runtime/eigen.py over SciPy eigh_tridiagonal / solve_banded / brentq).
# psi'' as a function of (x, psi, E); the same in tests/eigen.rs (by name).
def _fwell(x):
    return 0.0 if abs(x) < 1.0 else 50.0


EIGEN_CASES = [
    # name, psi''(x, p, E), a, b, N, grid
    ("harmonic", lambda x, p, E: (x * x - 2.0 * E) * p, -10.0, 10.0, 4, 2000),
    ("box", lambda x, p, E: -2.0 * E * p, 0.0, 1.0, 3, 1000),
    ("finite_well", lambda x, p, E: 2.0 * (_fwell(x) - E) * p, -4.0, 4.0, 3, 2000),
    ("coulomb", lambda x, p, E: (-2.0 / x - 2.0 * E) * p, 0.0, 60.0, 3, 4000),
    ("double_well", lambda x, p, E: 2.0 * (10.0 * (x * x - 4.0) * (x * x - 4.0) - E) * p, -5.0, 5.0, 2, 2000),
    ("tilted_double", lambda x, p, E: 2.0 * (10.0 * (x * x - 4.0) * (x * x - 4.0) + 1e-9 * x - E) * p, -5.0, 5.0, 2,
     2000),
    ("morse", lambda x, p, E: 2.0 * (8.0 * (1.0 - exp(-(x - 1.0))) * (1.0 - exp(-(x - 1.0))) - E) * p, 0.0, 12.0, 3,
     3000),
]
EIGEN_SAMPLES = [0.13, 0.31, 0.5, 0.62, 0.87]


def gen_eigen():
    from fermium.runtime.eigen import eigen_solve, EigenFail
    w = Writer("eigen.txt", """
v1's eigenvalue problems (fermium.runtime.eigen.eigen_solve), per method (matrix, shooting).
name/method N E1..EN [psi_k(x_i) psi_k'(x_i) at i = round(f*(len-1)) for f in EIGEN_SAMPLES, k = 1..N] nwarn warn_k warn_rel""")
    for method in ("matrix", "shooting"):
        for name, f2, a, b, N, grid in EIGEN_CASES:
            key = f"{name}/{method}"
            warns = []
            try:
                xs, ys, dys, E = eigen_solve(lambda x, y: [y[1], f2(x, y[0], y[2]), 0.0], a, b, N, grid, method,
                                             warn=lambda k, rel: warns.append((k, rel)))
            except EigenFail as fl:
                w.row(key, "ERR", fl.message.replace(" ", "_"))
                continue
            ncol = 3 * N
            vals = [float(N)] + E
            for k in range(N):
                for fr in EIGEN_SAMPLES:
                    i = int(round(fr * (len(xs) - 1)))
                    vals += [ys[i * ncol + 2 * k], ys[i * ncol + 2 * k + 1]]
            vals += [float(len(warns))] + (list(warns[0]) if warns else [0.0, 0.0])
            w.row(key, *vals)
    w.close()


# --------------------------------------------------------------------------------------- linalg
# v1's fermium/linalg.py (n <= 4) and linalg_big.py (n > 4) with FloatOps (what both back ends compute).
def gen_linalg():
    from fermium import linalg, linalg_big
    ops = linalg.FloatOps
    w = Writer("linalg.txt", """
v1's small/big linear algebra (fermium.linalg / linalg_big with FloatOps).
name:A a...  name:B b...  name:M m... (SPD)  then  name:det d  name:solve x...  name:inv x...  name:eig vals... vecs...  name:geig vals... vecs...""")
    for n in (2, 3, 4, 5, 8, 16):
        la = linalg_big if linalg_big.is_big(n) else linalg
        for variant in range(2):
            name = f"n{n}v{variant}"
            A = [sin(1.3 * (i + 1) + 0.7 * variant) * 3.0 + (4.0 if i % (n + 1) == 0 else 0.0) for i in range(n * n)]
            if variant == 1:
                A = [float(round(x * 4)) / 2 for x in A]           # half-integers: exact arithmetic paths
            S = [0.5 * (A[i * n + j] + A[j * n + i]) for i in range(n) for j in range(n)]
            B = [cos(0.9 * (i + 1)) for i in range(n)]
            M = [(n + 1.0 if i == j else 0.3 / (1 + abs(i - j))) for i in range(n) for j in range(n)]
            w.row(name + ":A", *A)
            w.row(name + ":B", *B)
            w.row(name + ":M", *M)
            w.row(name + ":det", la.det(ops, A, n))
            x = la.solve(ops, A, n, B, 1)[0]
            w.row(name + ":solve", *x)
            w.row(name + ":inv", *la.inverse(ops, A, n, 1.0, 0.0)[0])
            vals, vecs = la.jacobi_eigen(ops, S, n)
            w.row(name + ":eig", *vals, *vecs)
            gv = la.generalized_eigen(ops, S, M, n)
            w.row(name + ":geig", *gv[0], *gv[1])
    w.close()


# --------------------------------------------------------------------------------------- fft
# v1's spectrum (fermium/runtime/spectral.py over numpy.fft). Inputs by formula (same in tests/fft.rs):
# x_j = sin(0.37 j + 0.1) + 0.5 cos(0.013 j j), y_j = cos(1.1 j) * 0.5
FFT_SIZES = [1, 2, 3, 4, 5, 7, 8, 12, 16, 30, 97, 100, 128, 210, 256, 1000, 1024, 1031, 2003, 4096]


def gen_fft():
    from fermium.runtime.spectral import spectrum
    w = Writer("fft.txt", """
v1's spectrum() over numpy.fft: per size n and kind, all outputs (n <= 128) or 16 evenly spaced samples + the sum of squares.
n:kind values...""")
    for n in FFT_SIZES:
        x = [sin(0.37 * j + 0.1) + 0.5 * cos(0.013 * j * j) for j in range(n)]
        y = [cos(1.1 * j) * 0.5 for j in range(n)]
        z = [v for pair in zip(x, y) for v in pair]
        for kind in range(9):
            if kind == 4:
                out = spectrum(4, x, y)
            elif kind in (6, 7):
                out = spectrum(kind, z)
            else:
                out = spectrum(kind, x, dt=0.01)
            if len(out) > 256:
                idx = [int(round(i * (len(out) - 1) / 15)) for i in range(16)]
                vals = [out[i] for i in idx] + [sum(v * v for v in out)]
            else:
                vals = list(out)
            w.row(f"{n}:{kind}", *vals)
    w.close()


# --------------------------------------------------------------------------------------- special
# v1's special functions: the C library (what compiled v1 calls: erf erfc tgamma lgamma jn yn), v1's own
# besseli/besselk/ellipk/ellipe (fermium/special.py), and SciPy as an independent reference.
SPECIAL_X = [-30.0, -5.5, -2.5, -1.0, -0.3, -1e-8, 0.0, 1e-300, 1e-8, 0.1, 0.5, 1.0, 1.5, 2.0, 2.404825557695773,
             3.0, 5.0, 7.5, 10.0, 17.3, 25.0, 50.0, 100.0, 170.5, 300.0, 1e3, 1e5]
SPECIAL_N = [0, 1, 2, 3, 5, 10, 30, -1, -4]
SPECIAL_M = [-5.0, -1.0, 0.0, 1e-10, 0.1, 0.5, 0.9, 0.99, 0.999999, 1 - 1e-12, 1.0]


def gen_special():
    import ctypes
    import ctypes.util
    import scipy.special as sc
    from fermium import special as S
    lib = ctypes.CDLL(ctypes.util.find_library("m"))
    for f in ("erf", "erfc", "tgamma", "lgamma"):
        getattr(lib, f).restype = ctypes.c_double
        getattr(lib, f).argtypes = [ctypes.c_double]
    for f in ("jn", "yn"):
        getattr(lib, f).restype = ctypes.c_double
        getattr(lib, f).argtypes = [ctypes.c_int, ctypes.c_double]
    w = Writer("special.txt", """
v1's special functions. fn:x v1 scipy   or   fn:n:x v1 scipy   or   ellip:m K E K_scipy E_scipy""")
    for x in SPECIAL_X:
        w.row(f"erf:{r(x)}", lib.erf(x), sc.erf(x))
        w.row(f"erfc:{r(x)}", lib.erfc(x), sc.erfc(x))
        w.row(f"gamma:{r(x)}", lib.tgamma(x), sc.gamma(x))
        w.row(f"lgamma:{r(x)}", lib.lgamma(x), sc.gammaln(x))
    for n in SPECIAL_N:
        for x in SPECIAL_X:
            if x < 0 and n not in (0, 1):
                continue
            w.row(f"besselj:{n}:{r(x)}", lib.jn(n, x), sc.jv(n, x))
            if x > 0:
                w.row(f"bessely:{n}:{r(x)}", lib.yn(n, x), sc.yn(n, x))
            if abs(x) <= 300:
                w.row(f"besseli:{n}:{r(x)}", S.besseli(n, x), sc.iv(n, x))
            if 1e-100 < x <= 700:
                w.row(f"besselk:{n}:{r(x)}", S.besselk(n, x), sc.kn(abs(n), x))
    for m in SPECIAL_M:
        w.row(f"ellip:{r(m)}", S.ellipk(m), S.ellipe(m), sc.ellipk(m), sc.ellipe(m))
    w.close()


# --------------------------------------------------------------------------------------- rng
def gen_rng():
    from fermium import rng
    w = Writer("rng.txt", """
v1's seeded RNG (fermium/rng.py): per seed, 20 rand(), then 20 randn(), then 5 rand(2, 7) interleaved with randn(1, 0.5).
seed:<s> values...   (seed:default = never seeded)""")
    for s in ["default", 0.0, 1.0, 42.0, -7.0, 3.9, 123456789.0, 1e18, 1e19, math.nan, -2.5e17]:
        st = list(rng.DEFAULT_STATE)
        if s != "default":
            rng.seed(st, s)
        vals = [rng.rand(st) for _ in range(20)] + [rng.randn(st) for _ in range(20)]
        for _ in range(5):
            vals.append(2.0 + (7.0 - 2.0) * rng.rand(st))
            vals.append(1.0 + 0.5 * rng.randn(st))
        w.row(f"seed:{s if s == 'default' else r(s)}", *vals)
    w.close()


# --------------------------------------------------------------------------------------- pde
# v1's pde_solve (fermium/runtime/pde.py over scipy.sparse splu). Probes f(x, [u, ux, uxx, t, ut, i]) ->
# [rhs, u0, phase0, v0, left, right]; the same in tests/pde.rs (by name).
def _barrier(x):
    return 1.0 if abs(x) < 0.5 else 0.0


PDE_CASES = [
    # name, probe, xa, xb, t0, t1, options
    ("heat_cn", lambda x, a: [0.1 * a[2], sin(pi * x) + 0.3 * sin(3 * pi * x), 0.0, 0.0, 0.0, 0.0], 0.0, 1.0, 0.0,
     0.5, dict(grid=100)),
    ("heat_jump", lambda x, a: [a[2], 0.0, 0.0, 0.0, 1.0, 0.0], 0.0, 1.0, 0.0, 0.2, dict(grid=50)),
    ("heat_neumann_step", lambda x, a: [0.5 * a[2] - 0.2 * a[1], cos(pi * x), 0.0, 0.0, 0.0, 0.3], 0.0, 1.0, 0.0,
     1.0, dict(grid=80, step=0.05, bc=(1, 1))),
    ("heat_implicit_src", lambda x, a: [a[2] - a[0] + sin(3 * a[3]) * x, x * (1 - x), 0.0, 0.0, 0.0, 0.0], 0.0, 1.0,
     0.0, 2.0, dict(grid=60, method="implicit", tdep=True)),
    ("heat_explicit", lambda x, a: [a[2], exp(-40 * (x - 0.3) * (x - 0.3)), 0.0, 0.0, 0.0, 0.0], 0.0, 1.0, 0.0, 0.05,
     dict(grid=40, method="explicit")),
    ("tdse_free", lambda x, a: [a[5] * (0.5 * a[2]), exp(-(x + 5) * (x + 5) / 4), 2.0 * x, 0.0, 0.0, 0.0], -20.0,
     20.0, 0.0, 2.0, dict(grid=400, is_complex=True)),
    ("tdse_barrier", lambda x, a: [a[5] * (0.5 * a[2] - _barrier(x) * a[0]), exp(-(x + 5) * (x + 5) / 4), 1.5 * x,
                                   0.0, 0.0, 0.0], -20.0, 20.0, 0.0, 3.0, dict(grid=400, is_complex=True)),
    ("wave", lambda x, a: [4.0 * a[2], exp(-50 * (x - 0.5) * (x - 0.5)), 0.0, 0.0, 0.0, 0.0], 0.0, 1.0, 0.0, 1.0,
     dict(grid=200, order=2)),
    ("wave_damped", lambda x, a: [a[2] - 0.5 * a[4], sin(pi * x), 0.0, 1.0, 0.0, 0.0], 0.0, 1.0, 0.0, 2.0,
     dict(grid=100, order=2, step=0.004)),
    ("explicit_unstable", lambda x, a: [a[2], sin(pi * x), 0.0, 0.0, 0.0, 0.0], 0.0, 1.0, 0.0, 0.1,
     dict(grid=100, method="explicit", step=0.01)),
]


def gen_pde():
    from fermium.runtime.pde import pde_solve, PdeFail
    w = Writer("pde.txt", """
v1's PDE solver (fermium.runtime.pde.pde_solve). name nsnap M ncomp nwarn wkind west  t,y,dy at (snap, point) samples
snaps: 0, 1, n//3, n//2, n-1; points: round(f*(width-1)) for f in 0, 0.21, 0.5, 0.77, 1 over the row width  or  name ERR message""")
    for name, probe, xa, xb, t0, t1, opts in PDE_CASES:
        warns = []
        try:
            ts, ys, dys, ncomp, M = pde_solve(probe, xa, xb, t0, t1, warn=lambda k, e: warns.append((k, e)), **opts)
        except PdeFail as fl:
            w.row(name, "ERR", fl.message.replace(" ", "_"))
            continue
        width = (M + 1) * ncomp
        n = len(ts)
        vals = [float(n), float(M), float(ncomp), float(len(warns))] + (list(warns[0]) if warns else [0.0, 0.0])
        for s in (0, 1, n // 3, n // 2, n - 1):
            vals.append(ts[s])
            for f in (0.0, 0.21, 0.5, 0.77, 1.0):
                i = int(round(f * (width - 1)))
                vals += [ys[s * width + i], dys[s * width + i]]
        w.row(name, *vals)
    w.close()


SECTIONS = {"quad": gen_quad, "ode": gen_ode, "stiff": gen_stiff, "fit": gen_fit, "roots": gen_roots,
            "eigen": gen_eigen, "linalg": gen_linalg, "fft": gen_fft, "special": gen_special, "rng": gen_rng,
            "pde": gen_pde}

if __name__ == "__main__":
    todo = sys.argv[1:] or list(SECTIONS)
    for s in todo:
        SECTIONS[s]()
