//! The unit catalogue in the language specification (docs/spec/units.md §3.1) is generated from the unit
//! database and must stay equal to it (spec D1, DECISIONS D351). To regenerate it after changing the database:
//! `FERMIUM_UPDATE_SPEC=1 cargo test -p fermium-units --test spec_catalogue`.
use fermium_units::db::{lookup_unit, unit_names, unit_prefixable};
use fermium_units::dim::format_dim;
use std::path::Path;

const BEGIN: &str = "<!-- BEGIN UNIT CATALOGUE (generated by rust/crates/fermium-units/tests/spec_catalogue.rs) -->\n";
const END: &str = "<!-- END UNIT CATALOGUE -->";

fn num(x: f64) -> String {
    if x == 0.0 || (1e-3..1e6).contains(&x.abs()) {
        format!("{x}")
    } else {
        format!("{x:e}")
    }
}

fn table() -> String {
    let mut s = String::from("| Unit | Dimension (SI base units) | 1 unit in SI | Prefixes |\n|---|---|---|---|\n");
    for name in unit_names() {
        let u = lookup_unit(name).expect("a catalogue name is a unit");
        let dim = format_dim(&u.dim);
        let dim = if dim.is_empty() { "1".to_string() } else { dim };
        let si = if u.affine() {
            format!("x × {} + {} K", num(u.factor), num(u.offset))
        } else {
            num(u.factor)
        };
        let pre = match unit_prefixable(name) {
            Some(true) => "yes",
            _ => "no",
        };
        s.push_str(&format!("| `{name}` | {dim} | {si} | {pre} |\n"));
    }
    s
}

#[test]
fn spec_unit_catalogue_is_the_database() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../docs/spec/units.md");
    let text = std::fs::read_to_string(&path).unwrap();
    let b = text.find(BEGIN).expect("units.md has the generated catalogue's BEGIN marker") + BEGIN.len();
    let e = text[b..].find(END).expect("units.md has the END marker") + b;
    let want = table();
    if std::env::var("FERMIUM_UPDATE_SPEC").is_ok() {
        std::fs::write(&path, format!("{}{}{}", &text[..b], want, &text[e..])).unwrap();
        return;
    }
    assert!(text[b..e] == want, "docs/spec/units.md §3.1 is not the unit database; regenerate it with \
                                 FERMIUM_UPDATE_SPEC=1 cargo test -p fermium-units --test spec_catalogue");
}

/// Every unit written in backticks in units.md's §3 prose (the derived-unit list) is a unit.
#[test]
fn spec_units_named_in_prose_exist() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../docs/spec/units.md");
    let text = std::fs::read_to_string(path).unwrap();
    let line = text.lines().find(|l| l.starts_with("(`N J W")).expect("the derived-unit list in §3");
    let list = line.split('`').nth(1).unwrap();
    let missing: Vec<&str> = list.split_whitespace().filter(|n| lookup_unit(n).is_none()).collect();
    assert!(missing.is_empty(), "units.md §3 names units the database doesn't have: {missing:?}");
}
