[package]
name = "fermium-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "fermium"
path = "src/main.rs"

[dependencies]
fermium-syntax = { path = "../fermium-syntax" }
fermium-check = { path = "../fermium-check" }
fermium-codegen = { path = "../fermium-codegen" }
fermium-fmt = { path = "../fermium-fmt" }
fermium-ir = { path = "../fermium-ir" }
